// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorldApi.Contexts;

#nullable disable

namespace SportsWorldApi.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251210014816_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SportsWorldApi.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Female",
                            Image = "valentina_shevchenko.png",
                            Name = "Valentina Shevchenko",
                            Price = 1000000,
                            PurchaseStatus = false
                        });
                });

            modelBuilder.Entity("SportsWorldApi.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneyLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneySpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoneyLeft = 10000,
                            MoneySpent = 0,
                            NumberOfPurchases = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
