// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorldApi.Contexts;

#nullable disable

namespace SportsWorldApi.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251210024443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SportsWorldApi.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Female",
                            Image = "valentina_shevchenko.png",
                            Name = "Valentina Shevchenko",
                            Price = 1800000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 2,
                            Gender = "Female",
                            Image = "zhang_weili.png",
                            Name = "Zhang Weili",
                            Price = 1700000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 3,
                            Gender = "Female",
                            Image = "rose_namajunas.png",
                            Name = "Rose Namajunas",
                            Price = 1200000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 4,
                            Gender = "Female",
                            Image = "amanda_nunes.png",
                            Name = "Amanda Nunes",
                            Price = 2000000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 5,
                            Gender = "Female",
                            Image = "holly_holm.png",
                            Name = "Holly Holm",
                            Price = 900000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 6,
                            Gender = "Female",
                            Image = "julianna_pena.png",
                            Name = "Julianna Peña",
                            Price = 1100000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 7,
                            Gender = "Female",
                            Image = "alexa_grasso.png",
                            Name = "Alexa Grasso",
                            Price = 1500000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 8,
                            Gender = "Female",
                            Image = "tatiana_suarez.png",
                            Name = "Tatiana Suarez",
                            Price = 1300000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 9,
                            Gender = "Female",
                            Image = "erin_blanchfield.png",
                            Name = "Erin Blanchfield",
                            Price = 950000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 10,
                            Gender = "Female",
                            Image = "raquel_pennington.png",
                            Name = "Raquel Pennington",
                            Price = 800000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 11,
                            Gender = "Male",
                            Image = "conor_mcgregor.png",
                            Name = "Conor McGregor",
                            Price = 2000000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 12,
                            Gender = "Male",
                            Image = "jon_jones.png",
                            Name = "Jon Jones",
                            Price = 2200000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 13,
                            Gender = "Male",
                            Image = "israel_adesanya.png",
                            Name = "Israel Adesanya",
                            Price = 1600000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 14,
                            Gender = "Male",
                            Image = "alexander_volkanovski.png",
                            Name = "Alexander Volkanovski",
                            Price = 1500000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 15,
                            Gender = "Male",
                            Image = "khabib_nurmagomedov.png",
                            Name = "Khabib Nurmagomedov",
                            Price = 2100000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 16,
                            Gender = "Male",
                            Image = "leon_edwards.png",
                            Name = "Leon Edwards",
                            Price = 1400000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 17,
                            Gender = "Male",
                            Image = "sean_omalley.png",
                            Name = "Sean O’Malley",
                            Price = 1300000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 18,
                            Gender = "Male",
                            Image = "max_holloway.png",
                            Name = "Max Holloway",
                            Price = 1200000,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 19,
                            Gender = "Male",
                            Image = "charles_oliveira.png",
                            Name = "Charles Oliveira",
                            Price = 1900000,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 20,
                            Gender = "Male",
                            Image = "justin_gaethje.png",
                            Name = "Justin Gaethje",
                            Price = 1000000,
                            PurchaseStatus = true
                        });
                });

            modelBuilder.Entity("SportsWorldApi.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneyLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneySpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoneyLeft = 100000000,
                            MoneySpent = 0,
                            NumberOfPurchases = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
